spring:
  application:
    name: client-application
  security:
    oauth2:
      client:
        registration:
          app-client:
            provider: app-provider
            client-id: app-client
            client-secret: app-secret
            authorization-grant-type: client_credentials
            scope:
              - read
        provider:
          app-provider:
            token-uri: http://localhost:9000/oauth2/token
